name: build apps

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_web_app:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clippy check
        run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
  build_web_app:
    runs-on: ubuntu-latest
    needs: check_web_app
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --bin web_server
        
  upload_web_app:
    runs-on: ubuntu-latest
    needs: build_web_app
    steps:
      - uses: actions/checkout@v3
      - name: Build release
        run: |
          cargo build --release --bin web_server
          ls -la
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: web_server
          path: ./target/release/web_server
          retention-days: 90
      
  check_notification_daemon:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clippy check
        run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
  build_notification_daemon:
    runs-on: ubuntu-latest
    needs: check_notification_daemon
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --bin notification_daemon
        
  upload_notification_daemon:
    runs-on: ubuntu-latest
    needs: build_notification_daemon
    steps:
      - uses: actions/checkout@v3
      - name: Build release
        run: |
          cargo build --release --bin notification_daemon
          ls -la
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: notification_daemon
          path: ./target/release/notification_daemon
          retention-days: 90
